### ISSUE TITLE
Consolidate CRD

### ISSUE THREAD

**Issue by maltesander** [stackabletech/hbase-operator#161]
Currently we have a top level config (as discussed in CRD review):
```
apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: simple-hbase
spec:
  version: 2.4.11
  config:
    hdfsConfigMapName: simple-hdfs
    zookeeperConfigMapName: simple-hbase-znode
    hbaseManagesZk: false
    hbaseOpts:
    hbaseClusterDistributed: true
    hbaseRootdir: /hbase
```

The discovery fields `hdfsConfigMapName` and `zookeeperConfigMapName` should be moved to the top level.

Additionally, we will always use a managed ZooKeeper and always run in distributed mode. Therefore `hbaseManagesZk` and `hbaseClusterDistributed` can be removed.

This is done when the CR looks like:
```
apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: simple-hbase
spec:
  version: 2.4.11
  hdfsConfigMapName: simple-hdfs
  zookeeperConfigMapName: simple-hbase-znode
  config:
    hbaseRootdir: /hbase
```
and since this is breaking, the integration tests have been adapted as well.

TODOs:
- [x] Adapt the CRD to the proposed changes
- [x] Adapt the integration tests to the proposed CRD structure
