### ISSUE TITLE
The configuration of the hbaseRootdir at the role level is ignored

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/hbase-operator#555]
### Affected Stackable version

24.7.0

### Affected Apache HBase version

2.4.18, 2.6.0

### Current and expected behavior

The configuration of the hbaseRootdir at the role level is ignored:

```yaml
---
apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
spec:
  masters:
    config:
      hbaseRootdir: /test
```

The hbase-operator generates the following ConfigMap:

```yaml
---
apiVersion: v1
kind: ConfigMap
data:
  hbase-site.xml: |-
    <?xml version="1.0"?>
    <configuration>
      <property>
        <name>hbase.rootdir</name>
        <value>/hbase</value>
      </property>
    </configuration>
```

The configuration at the role-group level works as expected:

```yaml
---
apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
spec:
  masters:
    roleGroups:
      default:
        config:
          hbaseRootdir: /test
```

The hbase-operator generates the following ConfigMap:

```yaml
---
apiVersion: v1
kind: ConfigMap
data:
  hbase-site.xml: |-
    <?xml version="1.0"?>
    <configuration>
      <property>
        <name>hbase.rootdir</name>
        <value>/test</value>
      </property>
    </configuration>
```

Other configuration properties could be affected as well.

### Would you like to work on fixing this bug?

None
