### ISSUE TITLE
Zookeeper chroot not respected when set via hbase-site.xml zookeeper.znode.parent

### ISSUE THREAD

**Issue by radekg** [stackabletech/hbase-operator#614]
### Current and expected behavior

Current behavior is that a HBase cluster started with the config like below:

```yaml
---
apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: simple-hbase
spec:
  image:
    productVersion: 2.4.18
    repo: docker.stackable.tech/stackable
  clusterConfig:
    hdfsConfigMapName: simple-hdfs
    zookeeperConfigMapName: simple-hbase-znode
  masters:
    configOverrides:
      hbase-size.xml:
        zookeeper.znode.parent: /change-me
    roleGroups:
      default:
        replicas: 1
  regionServers:
    configOverrides:
      hbase-size.xml:
        zookeeper.znode.parent: /change-me
    roleGroups:
      default:
        config:
          resources:
            cpu:
              min: 300m
              max: "3"
            memory:
              limit: 3Gi
        replicas: 1
  restServers:
    configOverrides:
      hbase-size.xml:
        zookeeper.znode.parent: /change-me
    roleGroups:
      default:
        replicas: 1
```

does not respect the chroot setting. The config map still generates the random chroot.

The chroot config should be respected.

Alternatively - respect an existing config map and don't change the ZOOKEEPER_CHROOT if a config map has been found.

### Would you like to work on fixing this bug?

None

**Comment by maltesander** [comment]
Hi @radekg,

just a quick glance, you probably want to overwrite `hive-site.xml` :)

Cheers,
Malte

**Comment by radekg** [comment]
Hey @maltesander, yes, I mean hbase-site.xml. That kinda almost fixes the problem. With the fixed setting I can see the /change-me path and it does contain all expected zookeeper state for habse but the config map looks weird:

```yaml
apiVersion: v1
data:
  ZOOKEEPER: simple-zk-server-default-0.simple-zk-server-default.my-ns.svc.cluster.local:2282/znode-0747927d-92d4-4490-b48d-f8303b299a5b
  ZOOKEEPER_CHROOT: /znode-0747927d-92d4-4490-b48d-f8303b299a5b
  ZOOKEEPER_CLIENT_PORT: "2282"
  ZOOKEEPER_HOSTS: simple-zk-server-default-0.simple-zk-server-default.my-ns.svc.cluster.local:2282
kind: ConfigMap
```

There's no /change-me in there.
